# Generated by Django 4.2.15 on 2025-03-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['id'], 'verbose_name_plural': '09. Banners'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id'], 'verbose_name_plural': '02. Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': '01. Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['id'], 'verbose_name_plural': '05. Product Colors'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['id'], 'verbose_name_plural': '04. Images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name_plural': '03. Products'},
        ),
        migrations.AlterModelOptions(
            name='productfuture',
            options={'ordering': ['id'], 'verbose_name_plural': '10. Future'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id'], 'verbose_name_plural': '11. Reviews'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['id'], 'verbose_name_plural': '06. Product Sizes'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['id'], 'verbose_name_plural': '08. Sliders'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'ordering': ['id'], 'verbose_name_plural': '07. Product Variants'},
        ),
    ]
