# Generated by Django 4.2.15 on 2025-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
